baseURL = "https://mmaxence.me"
languageCode = "en-us"
pluralizelisttitles = false
theme = "ananke"
title = "Product Designer, CDO at buzzvil"
Author = "Maxence Mauduit"
enableRobotsTXT = "true"
summaryLength = 30

[params]
  custom_css = ["dist/css/style.css"]
  custom_js = ["dist/js/script.js"]
  author = "Maxence Mauduit"
  description = "Product Manager, Head of Design at buzzvil"
  twitter = "https://twitter.com/mmaxence"
  linkedin = "https://www.linkedin.com/in/mmaxence/"
  github = "https://github.com/mmaxence"
  medium = "https://medium.com/@mmaxence"
  show_reading_time = true
  favicon = "images/favicon.png"

[markup.goldmark.renderer]
  unsafe= true

  
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
  
[menu]
  [[menu.main]]
    name = "Experience"
    title = "My timeline"
    url = "/timeline/"
    weight = -140
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "blog section"
    url = "/blog/"
    weight = -130
  [[menu.main]]
    identifier = "Shelf"
    name = "Shelf"
    title = "shelf"
    url = "/library/"
    slug = "shelf"
    weight = -110
  #[[menu.main]]
  #  name = "Materials"
  #  title = "My Materials"
  #  url = "/materials/"
  #  slug = "materials"
  #  weight = -150